#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

touch cwo.foam

runApplication blockMesh

runApplication $(getApplication)

runApplication foamLog log.$(getApplication)

#------------------------------------------------------------------------------
